In [1]:
!pip install investpy

Collecting investpy
  Downloading investpy-1.0.8.tar.gz (4.4 MB)
     |████████████████████████████████| 4.4 MB 4.3 MB/s
Collecting Unidecode>=1.1.1
  Downloading Unidecode-1.3.4-py3-none-any.whl (235 kB)
     |████████████████████████████████| 235 kB 33.5 MB/s
Requirement already satisfied: setuptools>=41.2.0 in /usr/local/lib/python3.7/dist-packages (from investpy) (57.4.0)
Requirement already satisfied: numpy>=1.17.2 in /usr/local/lib/python3.7/dist-packages (from investpy) (1.21.6)
Requirement already satisfied: pandas>=0.25.1 in /usr/local/lib/python3.7/dist-packages (from investpy) (1.3.5)
Collecting lxml>=4.4.1
  Downloading lxml-4.8.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 33.2 MB/s
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.7/dist-packages (from investpy) (2.23.0)
Requirement already satisfied: pytz>=2019.3 in /usr/local/lib/python3.7/dist-packages (from investpy) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.1->investpy) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.1->investpy) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.22.0->investpy) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.22.0->investpy) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.22.0->investpy) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.22.0->investpy) (1.24.3)
Building wheels for collected packages: investpy
  Building wheel for investpy (setup.py) ... done
  Created wheel for investpy: filename=investpy-1.0.8-py3-none-any.whl size=4481592 sha256=c8d90cfc58f565721d79078f81414c8f371885deaecd18532bba91e94a44d7f1
  Stored in directory: /root/.cache/pip/wheels/96/a8/a5/0d33c72eaf00b41df7b9dc1e15d2b7c7154b3f1379ed350211
Successfully built investpy
Installing collected packages: Unidecode, lxml, investpy
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6
Successfully installed Unidecode-1.3.4 investpy-1.0.8 lxml-4.8.0

In [2]:
import pandas as pd
import numpy as np
import investpy

In [ ]:
investpy.stocks.get_stocks_overview('united states', as_json=False)

          country                 name  ...  turnover  currency
0   united states               Boeing  ...   9960000       USD
1   united states       General Motors  ...  15740000       USD
2   united states              Chevron  ...  10370000       USD
3   united states            Citigroup  ...  18640000       USD
4   united states      Bank of America  ...  34730000       USD
..            ...                  ...  ...       ...       ...
95  united states           Ciena Corp  ...    847240       USD
96  united states  IAC/InterActiveCorp  ...    511340       USD
97  united states               Intuit  ...   1290000       USD
98  united states              Expedia  ...   2360000       USD
99  united states         Trip.com ADR  ...   3960000       USD

[100 rows x 10 columns]

In [3]:
investpy.stocks.get_stocks_overview('india', as_json=False)

,country,name,symbol,last,high,low,change,change_percentage,turnover,currency
0,india,Aditya Birla Capital,ADTB,101.65,102.90,100.50,-0.45,-0.44%,2470000,INR
1,india,Hubtown,HUBT,61.95,62.35,59.90,+2.55,+4.29%,66550,INR
2,india,3i Infotech,TIIN,51.50,52.80,51.15,+0.550,+1.08%,239440,INR
3,india,3M India,TMIN,18500.00,18880.00,18410.00,-141.45,-0.76%,530,INR
4,india,ABB India,ABB,2315.30,2345.00,2301.05,+20.95,+0.91%,177840,INR
...,...,...,...,...,...,...,...,...,...,...
95,india,Cummins India Ltd,CUMM,1015.00,1028.00,1009.05,+6.90,+0.68%,298820,INR
96,india,D B Realty,DBRL,69.70,69.70,67.05,+3.30,+4.97%,292590,INR
97,india,Dabur India,DABU,513.75,515.25,502.00,+11.90,+2.37%,1040000,INR
98,india,DCM Shriram,DCMS,950.10,963.00,931.40,+23.20,+2.50%,79380,INR
99,india,DCW,DCWL,43.45,43.80,42.50,+1.15,+2.72%,411240,INR

In [7]:
pd.DataFrame(investpy.stocks.get_stocks_dict(country='india', columns=None, as_json=False))

,country,name,full_name,isin,currency,symbol
0,india,Aditya Birla Capital,Aditya Birla Capital Ltd,INE674K01013,INR,ADTB
1,india,Hubtown,Hubtown Ltd,INE703H01016,INR,HUBT
2,india,3i Infotech,3i Infotech Ltd,INE748C01020,INR,TIIN
3,india,3M India,3M India Ltd.,INE470A01017,INR,TMIN
4,india,ABB India,ABB India Ltd,INE117A01022,INR,ABB
...,...,...,...,...,...,...
1706,india,G K P Printing,G K P Printing & Packaging Ltd,INE05QJ01015,INR,GKPP
1707,india,Vivid Mercantile,Vivid Mercantile Ltd,INE647Z01017,INR,VIVD
1708,india,White Organic,White Organic Retail Ltd,INE06CG01019,INR,WHIE
1709,india,Parshva Enterprises,Parshva Enterprises Ltd,INE05MV01019,INR,PAHV
1710,india,SK International Export,SK International Export Ltd,INE04ST01013,INR,SKIN

1711

In [ ]:
investpy.stocks.get_stocks_overview('india', as_json=False)

   country                               name  ... turnover  currency
0    india               Aditya Birla Capital  ...  1890000       INR
1    india                            Hubtown  ...    38680       INR
2    india                        3i Infotech  ...    30340       INR
3    india                           3M India  ...     3700       INR
4    india                          ABB India  ...   216360       INR
..     ...                                ...  ...      ...       ...
95   india                        Cox & Kings  ...   175440       INR
96   india                             CRISIL  ...   205560       INR
97   india  CG Power and Industrial Solutions  ...   742590       INR
98   india                  Cummins India Ltd  ...   321800       INR
99   india                         D B Realty  ...   888450       INR

[100 rows x 10 columns]

In [ ]:
investpy.get_stock_information('BA',country='united states')

  Stock Symbol  Prev. Close  ... Shares Outstanding  Next Earnings Date
0           BA       233.09  ...        587699224.0          26/01/2022

[1 rows x 16 columns]

In [ ]:
search_result = investpy.search_quotes(text='hind', products=['stocks'],countries=['india'], n_results=1)#products=['stocks']
print(search_result)

{"id_": 18185, "name": "Hindustan Unilever Ltd.", "symbol": "HLL", "country": "india", "tag": "/equities/hindustan-unilever", "pair_type": "stocks", "exchange": "NSE"}

In [ ]:
#investpy.indices.get_indices_list(country='united states')
# countries  = ['united states', 'india','japan','china']

sample  = investpy.stocks.get_stocks_dict(country='india', columns=None, as_json=False)
sample_df = pd.DataFrame(sample)
sample_df

     country                     name  ... currency symbol
0      india     Aditya Birla Capital  ...      INR   ADTB
1      india                  Hubtown  ...      INR   HUBT
2      india              3i Infotech  ...      INR   TIIN
3      india                 3M India  ...      INR   TMIN
4      india                ABB India  ...      INR    ABB
...      ...                      ...  ...      ...    ...
1706   india           G K P Printing  ...      INR   GKPP
1707   india         Vivid Mercantile  ...      INR   VIVD
1708   india            White Organic  ...      INR   WHIE
1709   india      Parshva Enterprises  ...      INR   PAHV
1710   india  SK International Export  ...      INR   SKIN

[1711 rows x 6 columns]

In [ ]:
codes = sample_df.symbol

In [ ]:
# india_df =  pd.DataFrame()
# for stock in codes:
#     df = investpy.get_stock_information(stock= stock, country='india')
#     india_df = india_df.append(df).reset_index(drop=True)

# india_df

ConnectionError: ignored

In [ ]:
# US MARKETS

In [ ]:
us_data = pd.read_excel('/content/us_markets.xlsx')
us_data

                       Name  symbol Exchange  ...     Last  Chg. %  Market Cap
0                 Microsoft    MSFT   NASDAQ  ...   339.51  0.0102       2.55T
1                     Apple    AAPL   NASDAQ  ...   151.00  0.0067       2.48T
2                Alphabet C    GOOG   NASDAQ  ...  2981.50 -0.0021       1.98T
3                Alphabet A   GOOGL   NASDAQ  ...  2957.50 -0.0039       1.96T
4                Amazon.com    AMZN   NASDAQ  ...  3540.70 -0.0014       1.80T
..                      ...     ...      ...  ...      ...     ...         ...
95       Wells Fargo Pref L  WFC_pl     NYSE  ...  1500.71 -0.0035     200.84B
96           Wells Fargo&Co     WFC     NYSE  ...    50.37 -0.0139     200.84B
97  Wells Fargo & Co Pq ADR  WFC_pq     NYSE  ...    26.46 -0.0019     200.84B
98       Wells Fargo Pref R  WFC_pr     NYSE  ...    27.83 -0.0005     200.84B
99  Wells Fargo & Co Po ADR  WFC_po     NYSE  ...    25.00  0.0000     197.57B

[100 rows x 8 columns]

In [ ]:

us_df =  pd.DataFrame()
for each in us_data.symbol:
    print(each)
    try:
        df = investpy.get_stock_historical_data(stock=each, country='united states', from_date='01/01/2019', to_date='17/11/2021').reset_index(drop=False)
        df['symbol'] = each
        us_df = us_df.append(df).reset_index(drop=True)
    except RuntimeError:
        pass
us_df

MSFT
AAPL
GOOG
GOOGL
AMZN
TSLA
FB
NVDA
ASML
ADBE
NFLX
PYPL
CMCSA
CSCO
AVGO
COST
PEP
INTC
QCOM
AVGOP
AMD
INTU
AZN
TXN
RIVN
HON
TMUS
AMAT
CHTR
JD
SBUX
ABNB
ISRG
SNY
PDD
AMGN
TEAM
ADI
ADP
BKNG
MRNA
LCID
LRCX
MDLZ
MU
GILD
CME
ZM
CSX
MELI
BAC_pe
BAC_pl
BML_pl
BAC_pm
BML_pg
BML_ph
BML_pj
BRKa
BRKb
TSM
JPM
JPM_pc
BABA
V
JPM_pg
JPM_ph
JNJ
UNH
HD
WMT
BAC
MA
PG
CRM
DIS
PFE
XOM
NKE
WBK
ORCL
NVO
TM
TMO
KO
DPZ
ACN
LLY
ABT
CVX
DHR
VZ
MRK
DHR_pa
SHOP
ABBV
WFC_pl
WFC
WFC_pq
WFC_pr
WFC_po

            Date    Open    High     Low   Close    Volume Currency symbol
0     2019-01-02   99.55  101.75   98.94  101.12  35329344      USD   MSFT
1     2019-01-03  100.10  100.19   97.20   97.40  42578408      USD   MSFT
2     2019-01-04   99.72  102.51   98.93  101.93  44060620      USD   MSFT
3     2019-01-07  101.64  103.27  100.98  102.06  35656136      USD   MSFT
4     2019-01-08  103.04  103.97  101.71  102.80  31514416      USD   MSFT
...          ...     ...     ...     ...     ...       ...      ...    ...
57271 2021-11-10   49.74   50.77   49.68   50.36  19813964      USD    WFC
57272 2021-11-11   50.42   50.91   50.22   50.59  15624663      USD    WFC
57273 2021-11-12   50.68   51.00   50.37   50.96  17124728      USD    WFC
57274 2021-11-15   51.19   51.69   50.97   51.08  20110198      USD    WFC
57275 2021-11-16   51.11   51.18   50.17   50.37  18820052      USD    WFC

[57276 rows x 8 columns]

In [ ]:
us_final_df = us_df.merge(us_data,how='left',on='symbol')
us_final_df.to_csv('us_markets_data.csv',index = False)

In [ ]:
us_final_df

            Date    Open    High     Low  ...  Industry    Last  Chg. % Market Cap
0     2019-01-02   99.55  101.75   98.94  ...  Software  339.51  0.0102      2.55T
1     2019-01-03  100.10  100.19   97.20  ...  Software  339.51  0.0102      2.55T
2     2019-01-04   99.72  102.51   98.93  ...  Software  339.51  0.0102      2.55T
3     2019-01-07  101.64  103.27  100.98  ...  Software  339.51  0.0102      2.55T
4     2019-01-08  103.04  103.97  101.71  ...  Software  339.51  0.0102      2.55T
...          ...     ...     ...     ...  ...       ...     ...     ...        ...
57271 2021-11-10   49.74   50.77   49.68  ...     Banks   50.37 -0.0139    200.84B
57272 2021-11-11   50.42   50.91   50.22  ...     Banks   50.37 -0.0139    200.84B
57273 2021-11-12   50.68   51.00   50.37  ...     Banks   50.37 -0.0139    200.84B
57274 2021-11-15   51.19   51.69   50.97  ...     Banks   50.37 -0.0139    200.84B
57275 2021-11-16   51.11   51.18   50.17  ...     Banks   50.37 -0.0139    200.84B

[57276 rows x 15 columns]

# Indian Markets

In [ ]:
data = pd.read_excel('/content/ind_markets.xlsx')


hist_df =  pd.DataFrame()
for each in data.symbol:
    print(each)
    try:
        df = investpy.get_stock_historical_data(stock=each, country='india', from_date='01/01/2019', to_date='17/11/2021').reset_index(drop=False)
        df['symbol'] = each
        hist_df = hist_df.append(df).reset_index(drop=True)
    except RuntimeError:
        pass

final_df = hist_df.merge(data,how='left',on='symbol')
final_df.to_csv('ind_markets_data.csv',index = False)
final_df

RELI
TCS
HDBK
INFY
HLL
HDFC
ICBK
BJFN
SBI
BRTI
KTKM
WIPR
AVEU
HCLT
ASPN
ITC
BJFS
LART
BASF
MRTI
ULTC
TITN
AXBK
ADAI
ADNA
TAMO
ONGC
SUN
SIEM
NEST
ADEL
ADAG
SKFB
JSTL
APSE
TISC
HDFL
TEML
HZNC
PGRD
NTPC
LRTI
DIVI
VDAN
ZOMT
PIDI
SBIL
IOC
GRAS
TAMdv
RELI
TCS
HDBK
INFY
HLL
HDFC
ICBK
BJFN
SBI
BRTI
KTKM
WIPR
AVEU
HCLT
ASPN
ITC
BJFS
LART
BASF
MRTI
ULTC
TITN
AXBK
ADAI
ADNA
ONGC
SUN
SIEM
NEST
ADEL
ADAG
APSE
TISC
HDFL
TEML
HZNC
PGRD
NTPC
LRTI
DIVI
ZOMT
PIDI
SBIL
IOC
GRAS
TAMdv
TAMO
DABU
MAHM
BAJA

#Japan Markets

In [ ]:
data = pd.read_excel('/content/jp_markets.xlsx')


hist_df =  pd.DataFrame()
for each in data.symbol:
    print(each)
    try:
        df = investpy.get_stock_historical_data(stock=str(each), country='japan', from_date='01/01/2019', to_date='17/11/2021').reset_index(drop=False)
        df['symbol'] = each
        hist_df = hist_df.append(df).reset_index(drop=True)
    except RuntimeError:
        pass

final_df = hist_df.merge(data,how='left',on='symbol')
final_df.to_csv('japan_markets_data.csv',index = False)
final_df

7203
6861
6758
9984
6098
9432
8035
4063
8306
6594
9983
9433
9434
6367
6501
4519
7741
6902
4661
4689
7974
4568
7267
6981
8316
8058
4502
8001
6273
6954
2413
3382
8031
2914
8766
6702
8411
4543
4503
4901
9613
5108
7182
7733
6178
9022
6752
6503
6201
4911

            Date    Open    High  ...   Last  Chg. %  Market Cap
0     2019-01-04  6180.0  6360.0  ...  2.13K   -0.63      29.47T
1     2019-01-07  6495.0  6622.0  ...  2.13K   -0.63      29.47T
2     2019-01-08  6610.0  6687.0  ...  2.13K   -0.63      29.47T
3     2019-01-09  6712.0  6715.0  ...  2.13K   -0.63      29.47T
4     2019-01-10  6630.0  6714.0  ...  2.13K   -0.63      29.47T
...          ...     ...     ...  ...    ...     ...         ...
34891 2021-11-11  7230.0  7326.0  ...  7.52K    0.63       3.01T
34892 2021-11-12  7355.0  7517.0  ...  7.52K    0.63       3.01T
34893 2021-11-15  7497.0  7539.0  ...  7.52K    0.63       3.01T
34894 2021-11-16  7468.0  7512.0  ...  7.52K    0.63       3.01T
34895 2021-11-17  7543.0  7579.0  ...  7.52K    0.63       3.01T

[34896 rows x 15 columns]

# China Markets

In [ ]:
data = pd.read_excel('/content/china_markets.xlsx')


hist_df =  pd.DataFrame()
for each in data.symbol:
    print(each)
    try:
        df = investpy.get_stock_historical_data(stock=str(each), country='china', from_date='01/01/2019', to_date='17/11/2021').reset_index(drop=False)
        df['symbol'] = each
        hist_df = hist_df.append(df).reset_index(drop=True)
    except RuntimeError or ConnectionError:
        pass

final_df = hist_df.merge(data,how='left',on='symbol')
final_df.to_csv('china_markets_data.csv',index = False)
final_df

600519
601398
601939
600036
601288
601318
601988
601857
601628
601658
601633
603288
600028
601012
600900
601888
603259
601166
600809
601088
601328
600276
600030
600309
601601
601899
600436
688981
600690
600000
600887
601919
600104
601138
603501
601816
600438
601066
601998
600406
601319
601668
600585
601995
600031
601818
601238
600905
601766
600111
300750
2594
858
333
2415
300760
300059
300999
1
568
2714
2475
2352
300015
2304
300014
2812
2142
2460
2
300274
300122
2371
651
725
300124
2241
776
2493
63
2466
300759
2129
2459
792
625
200725
338
596
2230
300347
2049
166
300896
300450
2709
661
3816
538
877

            Date    Open    High  ...     Last  Chg. %  Market Cap
0     2019-01-02  609.98  612.00  ...  1795.00 -0.0072       2.25T
1     2019-01-03  599.97  601.66  ...  1795.00 -0.0072       2.25T
2     2019-01-04  587.28  607.67  ...  1795.00 -0.0072       2.25T
3     2019-01-07  608.00  612.00  ...  1795.00 -0.0072       2.25T
4     2019-01-08  605.50  612.00  ...  1795.00 -0.0072       2.25T
...          ...     ...     ...  ...      ...     ...         ...
38350 2021-11-11   85.40   86.30  ...    80.97 -0.0016     126.62B
38351 2021-11-12   84.76   87.76  ...    80.97 -0.0016     126.62B
38352 2021-11-15   87.29   87.99  ...    80.97 -0.0016     126.62B
38353 2021-11-16   82.86   84.20  ...    80.97 -0.0016     126.62B
38354 2021-11-17   82.63   83.00  ...    80.97 -0.0016     126.62B

[38355 rows x 15 columns]

# UK Markets Data

In [ ]:
# 

data = pd.read_excel('/content/uk_markets.xlsx')


hist_df =  pd.DataFrame()
for each in data.symbol:
    print(each)
    try:
        df = investpy.get_stock_historical_data(stock=str(each), country='united kingdom', from_date='01/01/2019', to_date='17/11/2021').reset_index(drop=False)
        df['symbol'] = each
        hist_df = hist_df.append(df).reset_index(drop=True)
    except RuntimeError or ConnectionError:
        pass

final_df = hist_df.merge(data,how='left',on='symbol')
final_df.to_csv('uk_markets_data.csv',index = False)
final_df

TYT
0M69
0QYR
MELM
0RIH
0QIU
0QFP
0SJQ
KNM
0M2Z
RICO
0NC6
0XXV
0N4T
0NUG
0HTP
0NZF
0GRX
0RHE
0JN9
0HAU
0NOF
0O77
0QR4
0QQ6
0O84
0O87
0HBY
0QB8
0R87
0HC0
0HBP
0YSUa
RDSb
RDSa
0QBO
0QYF
0NZM
0NMK
0Q15
0R7S
0R7R
0YSVb
0RQP
0Q1G
0H6T
0QAH
0G8C
0QCV
0AI4

           Date     Open     High  ...    Last  Chg. %  Market Cap
0    2019-01-04   951.02   951.66  ...  1388.5 -0.0054       3.24T
1    2019-01-07   991.25   992.41  ...  1388.5 -0.0054       3.24T
2    2019-01-08  1008.33  1010.80  ...  1388.5 -0.0054       3.24T
3    2019-01-09  1044.90  1046.22  ...  1388.5 -0.0054       3.24T
4    2019-01-10  1038.30  1038.77  ...  1388.5 -0.0054       3.24T
...         ...      ...      ...  ...     ...     ...         ...
3298 2021-11-10    53.99    54.51  ...    57.5  0.0000     242.70B
3299 2021-11-11    53.90    54.08  ...    57.5  0.0000     242.70B
3300 2021-11-12    53.60    53.89  ...    57.5  0.0000     242.70B
3301 2021-11-15    53.62    53.65  ...    57.5  0.0000     242.70B
3302 2021-11-16    53.45    53.55  ...    57.5  0.0000     242.70B

[3303 rows x 15 columns]

#Commodities

In [ ]:
from_date = '01/01/2019'
to_date = '17/11/2021'
commodities = ['Gold','Silver','Copper','Crude Oil WTI','Natural Gas']
commodities_df =pd.DataFrame()

for each in commodities: 
    df = investpy.commodities.get_commodity_historical_data(each, from_date, to_date,country=None, as_json=False,order='ascending', interval='Daily').reset_index(drop=False)
    df['Commodity'] = each
    commodities_df = commodities_df.append(df).reset_index(drop=True)
    print(commodities_df)

          Date    Open     High      Low    Close  Volume Currency Commodity
0   2019-01-01  1284.7  1284.75  1282.85  1283.35       0      USD      Gold
1   2019-01-02  1349.5  1349.50  1349.50  1349.50     100      USD      Gold
2   2019-01-03  1359.8  1359.80  1359.80  1359.80      10      USD      Gold
3   2019-01-04  1351.8  1351.80  1351.80  1351.00       1      USD      Gold
4   2019-01-07  1355.2  1355.20  1355.20  1355.20       7      USD      Gold
..         ...     ...      ...      ...      ...     ...      ...       ...
758 2021-11-11  1851.5  1868.70  1845.10  1863.90  205312      USD      Gold
759 2021-11-12  1864.3  1871.40  1847.50  1868.50  201358      USD      Gold
760 2021-11-15  1872.6  1873.00  1858.50  1866.60  221208      USD      Gold
761 2021-11-16  1864.9  1879.50  1851.00  1854.10       0      USD      Gold
762 2021-11-17  1852.0  1863.45  1851.15  1862.35       0      USD      Gold

[763 rows x 8 columns]
           Date      Open      High  ...  Volume  Currency  Commodity
0    2019-01-01  1284.700  1284.750  ...       0       USD       Gold
1    2019-01-02  1349.500  1349.500  ...     100       USD       Gold
2    2019-01-03  1359.800  1359.800  ...      10       USD       Gold
3    2019-01-04  1351.800  1351.800  ...       1       USD       Gold
4    2019-01-07  1355.200  1355.200  ...       7       USD       Gold
...         ...       ...       ...  ...     ...       ...        ...
1657 2021-11-12    25.350    25.470  ...   66390       USD     Silver
1658 2021-11-14    25.413    25.462  ...       0       USD     Silver
1659 2021-11-15    25.425    25.465  ...   68484       USD     Silver
1660 2021-11-16    25.135    25.490  ...       0       USD     Silver
1661 2021-11-17    24.878    25.177  ...       0       USD     Silver

[1662 rows x 8 columns]

/usr/local/lib/python3.7/dist-packages/investpy/commodities.py:529: Warning: Note that the displayed commodity data can differ depending on the country. If you want to retrieve copper data from either united states or united kingdom, specify the country parameter.
  warnings.warn(msg, Warning)

           Date       Open       High  ...  Volume  Currency  Commodity
0    2019-01-01  1284.7000  1284.7500  ...       0       USD       Gold
1    2019-01-02  1349.5000  1349.5000  ...     100       USD       Gold
2    2019-01-03  1359.8000  1359.8000  ...      10       USD       Gold
3    2019-01-04  1351.8000  1351.8000  ...       1       USD       Gold
4    2019-01-07  1355.2000  1355.2000  ...       7       USD       Gold
...         ...        ...        ...  ...     ...       ...        ...
2419 2021-11-11     4.3045     4.4320  ...   72511       USD     Copper
2420 2021-11-12     4.4030     4.4590  ...   48083       USD     Copper
2421 2021-11-15     4.4550     4.4890  ...   58383       USD     Copper
2422 2021-11-16     4.4115     4.4425  ...       0       USD     Copper
2423 2021-11-17     4.3460     4.3605  ...       0       USD     Copper

[2424 rows x 8 columns]
           Date     Open     High  ...  Volume  Currency      Commodity
0    2019-01-01  1284.70  1284.75  ...       0       USD           Gold
1    2019-01-02  1349.50  1349.50  ...     100       USD           Gold
2    2019-01-03  1359.80  1359.80  ...      10       USD           Gold
3    2019-01-04  1351.80  1351.80  ...       1       USD           Gold
4    2019-01-07  1355.20  1355.20  ...       7       USD           Gold
...         ...      ...      ...  ...     ...       ...            ...
3179 2021-11-11    81.41    82.33  ...  475436       USD  Crude Oil WTI
3180 2021-11-12    81.21    81.62  ...  390304       USD  Crude Oil WTI
3181 2021-11-15    80.66    81.20  ...  343484       USD  Crude Oil WTI
3182 2021-11-16    80.93    81.81  ...       0       USD  Crude Oil WTI
3183 2021-11-17    79.55    79.55  ...       0       USD  Crude Oil WTI

[3184 rows x 8 columns]
           Date      Open      High  ...  Volume  Currency    Commodity
0    2019-01-01  1284.700  1284.750  ...       0       USD         Gold
1    2019-01-02  1349.500  1349.500  ...     100       USD         Gold
2    2019-01-03  1359.800  1359.800  ...      10       USD         Gold
3    2019-01-04  1351.800  1351.800  ...       1       USD         Gold
4    2019-01-07  1355.200  1355.200  ...       7       USD         Gold
...         ...       ...       ...  ...     ...       ...          ...
3939 2021-11-11     4.917     5.176  ...  135953       USD  Natural Gas
3940 2021-11-12     5.129     5.141  ...  137099       USD  Natural Gas
3941 2021-11-15     4.903     5.065  ...  117666       USD  Natural Gas
3942 2021-11-16     5.058     5.394  ...       0       USD  Natural Gas
3943 2021-11-17     5.139     5.163  ...       0       USD  Natural Gas

[3944 rows x 8 columns]

In [ ]:
commodities_df.to_csv('commodity_prices_v1.csv',index=False)

In [ ]:
# !pip install yfinance
# import yfinance as yf
# yf.pdr_override()
# data = yf.download("SPY AAPL", start="2017-01-01", end="2017-04-30")

Requirement already satisfied: yfinance in /usr/local/lib/python3.7/dist-packages (0.1.66)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.9)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.1.5)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.6.4)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.23.0)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2021.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (3.0.4)
[*********************100%***********************]  2 of 2 completed

In [ ]:
# data

            Adj Close                  Close  ...        Open     Volume
                 AAPL         SPY       AAPL  ...         SPY       AAPL        SPY
Date                                          ...
2017-01-03  27.332470  206.871796  29.037500  ...  225.039993  115127600   91366500
2017-01-04  27.301874  208.102478  29.004999  ...  225.619995   84472400   78744400
2017-01-05  27.440718  207.937180  29.152500  ...  226.270004   88774400   78379000
2017-01-06  27.746632  208.681122  29.477501  ...  226.529999  127007600   71559900
2017-01-09  28.000776  207.992264  29.747499  ...  226.910004  134247600   46939700
...               ...         ...        ...  ...         ...        ...        ...
2017-04-24  33.947975  218.776566  35.910000  ...  237.179993   68537200  119209900
2017-04-25  34.158318  220.049530  36.132500  ...  237.910004   75486000   76698300
2017-04-26  33.957436  219.911133  35.919998  ...  238.509995   80164800   84702500
2017-04-27  33.983429  220.095627  35.947498  ...  238.770004   56985200   57410300
2017-04-28  33.950340  219.615967  35.912498  ...  238.899994   83441600   63532800

[81 rows x 12 columns]